###################################################################
# Project information
###################################################################
site_name:        ProGuard Core
site_description: The ProGuard Core library
site_author:      Guardsquare NV
copyright:        Copyright &copy; 2002-2020 Guardsquare NV

###################################################################
# Options
###################################################################
theme:
  name:       null
  custom_dir: ../../buildscripts/mkdocs/material
  logo:       img/core.png
  favicon:    img/guardsquare.png
  language:   en
  palette:    blue
  font:
  feature: 

docs_dir: md
site_dir: html

#extra_css: 
#  - extra.css

use_directory_urls: false
#strict: true # broken links are errors

###################################################################
# Theme specific
###################################################################
extra:
  #font:
  #  text: 'Droid Sans'
  #  code: 'Ubuntu Mono'
  social:
  - type: 'twitter'
    link: 'https://twitter.com/guardsquare'
  - type: 'linkedin'
    link: 'https://www.linkedin.com/company/guardsquare-nv'
  - type: 'facebook'
    link: 'https://www.facebook.com/guardsquare'
  #feature:
  #  tabs: true

###################################################################
# Extensions
###################################################################
markdown_extensions:
- attr_list
- admonition
- footnotes
- def_list

###################################################################
# Page tree
###################################################################
nav:
- Introduction:        index.md
- Reading classes:     reading.md
- Creating classes:    creating.md
- Editing classes:     editing.md
- Pattern matching:    patternmatching.md
- Analyzing code:      analyzing.md
- License:             license.md
- Downloads:           downloads.md
- Building:            building.md
- Release notes:       releasenotes.md
